services:
  sample-app:
    # example: ifconfig.co https://github.com/mpolden/echoip
    image: mpolden/echoip:latest
    command: -H X-Real-IP
  dynname-proxy:
    build: .
    ports:
      - 443:443
      - 80:80
    environment:
      - UPSTREAM_HTTP_HOST=sample-app
      - UPSTREAM_HTTP_PORT=8080
      - UPSTREAM_HTTPS_HOST=sample-app
      - UPSTREAM_HTTPS_PORT=8080
    links:
      - sample-app
    volumes:
      - "dynname:/opt/dynname/data"
      - "etc-letsencrypt:/etc/letsencrypt"
      - "var-lib-letsencrypt:/var/lib/letsencrypt"
volumes:
  etc-letsencrypt: {}
  var-lib-letsencrypt: {}
  dynname: {}
