services:
  sample-app:
    # example: echoip https://github.com/mpolden/echoip
    # The echoip service listens on port 8080.
    image: mpolden/echoip
    ports:
      - 8080:8080
    command:
      - -H
      - X-Real-IP
  dynname-proxy:
    image: yacchin1205/dynna.me:latest
    environment:
      # Etherpad Container Name(sample-app):echoip Port(8081)
      - UPSTREAM_HTTP_HOST=localhost
      - UPSTREAM_HTTP_PORT=8080
      - UPSTREAM_HTTPS_HOST=localhost
      - UPSTREAM_HTTPS_PORT=8080
    volumes:
      - "dynname:/opt/dynname/data"
      - "etc-letsencrypt:/etc/letsencrypt"
      - "var-lib-letsencrypt:/var/lib/letsencrypt"
    network_mode: 'host'
volumes:
  etc-letsencrypt: {}
  var-lib-letsencrypt: {}
  dynname: {}
