services:
  echoip:
    # example: echoip https://github.com/mpolden/echoip
    # The echoip service listens on port 8080.
    image: mpolden/echoip
    ports:
      - 8080:8080
    command:
      - -H
      - X-Real-IP
  etherpad:
    # example: etherpad https://github.com/ether/etherpad-lite
    # The Etherpad service listens on port 9001.
    # If you want to run it on ARM, specify yacchin1205/etherpad:develop
    image: etherpad/etherpad
    ports:
      - 9001:9001
  dynname-proxy:
    image: yacchin1205/dynna.me:latest
    volumes:
      - "./nginx.conf.j2:/opt/dynname/conf/nginx.conf.j2"
      - "dynname:/opt/dynname/data"
      - "etc-letsencrypt:/etc/letsencrypt"
      - "var-lib-letsencrypt:/var/lib/letsencrypt"
    network_mode: 'host'
volumes:
  etc-letsencrypt: {}
  var-lib-letsencrypt: {}
  dynname: {}
